version: "3.3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: deus
      POSTGRES_USER: deususer
      POSTGRES_PASSWORD: deuspass
  web:
    build: .
    command: python3 ./video_club/manage.py migrate
    command: python3 ./video_club/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
